# Generated by Django 5.1.1 on 2024-10-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_platform_alter_service_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
