# Generated by Django 5.1.1 on 2024-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
