# Generated by Django 5.1.1 on 2024-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
