# Generated by Django 5.1.1 on 2024-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
